languageCode = 'en-us'
title = 'rvdm.net'
theme = "anubis"
googleAnalytics: "G-CH1XZBV1KR"
enableRobotsTXT: true

params:
    author: "rvdm"
    dateFormat: "01-02-2006"
    readMore: true
    style: auto
    social:
    - id: github
      name: rvdm
    - id: twitter
      name: rvdm
